repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: no-commit-to-branch
    args: [--branch, master]
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.4.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]

####################################################################
#
# Python
#
####################################################################

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    #args: [--line-length=79]

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8

- repo: https://github.com/returntocorp/semgrep
  rev: 'v1.27.0'
  hooks:
  - id: semgrep
    args: ['--config', 'p/python', '--error', '--skip-unknown-extensions']
    exclude: "src/app.py"
